name: CodSpeed

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "version-*"]
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --group dev

      - name: Install CodSpeed
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/CodSpeedHQ/codspeed/releases/download/v4.16.2-alpha.1/codspeed-runner-installer.sh | sh

      - name: Run benchmarks
        run: codspeed run --mode simulation -- uv run pytest tests/benchmarks/ --codspeed

      # - name: Run benchmarks
      #   uses: CodSpeedHQ/action@3194d9a39c4d46684cb44bf7207fc56626aad8fd # v4.15.1
      #   with:
      #     # runner-version: v4.16.2-alpha.1
      #     mode: simulation
      #     run: uv run pytest tests/benchmarks/ --codspeed
